# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: 'Build Stage'  # Renamed the stage to "Build Stage"
  jobs:
  - job: BuildJob  # Renamed the job to "BuildJob"
    displayName: 'Build Application'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
      displayName: 'Use Python 3.9'

    - script: |
        python -m venv antenv
        source antenv/bin/activate
        source antenv/bin/pip install -r requirements.txt
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install waitress
        pip install gunicorn
        pip install -r requirements.txt
        antenv/bin/pip install waitress  # Use the relative path
      displayName: "Install requirements"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop
